services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $varDirectory: '%kernel.project_dir%/var'
            $environment: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
