services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $varDirectory: '%kernel.project_dir%/var'
            $environment: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Shared\UserInterface\Web\Controller\GraphQL:
        tags: [ controller.service_arguments ]
        arguments:
            $shouldHandleCORS: false
            $graphQLBatchingMethod: false

    App\Shared\UserInterface\Web\Controller\GraphQLPlayground:
        tags: [ controller.service_arguments ]
        arguments:
            $shouldHandleCORS: false
            $graphQLBatchingMethod: false
