RootQuery:
    type: object
    config:
        fields:
            products:
                args:
                    limit:
                        type: Int!
                    page:
                        type: Int!
                type: PaginatedProducts!
                resolve: '@=query("root_product_list", args)'
            cart:
                args:
                    id:
                        type: String!
                type: Cart
                resolve: '@=query("root_cart", args)'
